defaults:
  - _self_
  - model: Phi-3.5-1B-Instruct
  - trainer: finetune
  - data: finetune
  - collator: DataCollatorForSupervisedDatasetwithIndex
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null

trainer:
  args:
    remove_unused_columns: False

mode: train
task_name: ???